#!/usr/bin/env node
// Bundle lib/*.clj files + prejoined assets into a JS module for the virtual FS

const fs = require('fs');
const path = require('path');

const libDir = path.join(__dirname, '..', 'lib');
const prejoinedDir = path.join(__dirname, '..', 'bootstrap', 'prejoined');
const outFile = path.join(__dirname, 'public', 'vfs-bundle.js');

function collectFiles(dir, prefix) {
  const entries = {};
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      Object.assign(entries, collectFiles(path.join(dir, entry.name), relPath));
    } else if (entry.name.endsWith('.clj') || entry.name.endsWith('.cljc')) {
      entries[relPath] = fs.readFileSync(path.join(dir, entry.name), 'utf-8');
    }
  }
  return entries;
}

const files = collectFiles(libDir, 'lib');

// Add ALL prejoined files for the bootstrap compiler's fast batch path.
// This avoids re-reading core.clj (1.7s) on every eval.
for (const name of fs.readdirSync(prejoinedDir)) {
  const fullPath = path.join(prejoinedDir, name);
  if (fs.statSync(fullPath).isFile()) {
    files[`bootstrap/prejoined/${name}`] = fs.readFileSync(fullPath, 'utf-8');
  }
}

const js = `// Generated by build-vfs.js — do not edit\nwindow.VFS_BUNDLE = ${JSON.stringify(files)};\n`;

fs.writeFileSync(outFile, js);
console.log(`Bundled ${Object.keys(files).length} files (${(Buffer.byteLength(js) / 1024).toFixed(0)} KB)`);
